# Generated by Django 5.0.1 on 2024-02-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('time_c', models.DateTimeField(auto_now_add=True)),
                ('time_u', models.DateTimeField()),
                ('is_p', models.BooleanField()),
            ],
        ),
    ]
